version: "3"
services:
  db:
    image: mariadb:10.4
    container_name: "laravel-db"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker_db
      MYSQL_USER: test
      MYSQL_PASSWORD: testtest
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
  php:
    build: ./php
    container_name: "laravel-php"
    volumes:
      - ./source:/var/www/html
      - ./php/vhost.conf:/etc/apache2/conf-enabled/vhost.conf
    ports:
      - "8080:80"
